use sense_pi;
CREATE TABLE sense_hat_data (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
pitch INT(3),
yaw INT(3),
roll INT(3),
rec_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);